### ISSUE TITLE
Issue with news

### ISSUE THREAD

**Issue by qwertychouskie** [supertuxkart/stk-addons#111]
See pic:
![pic](https://i.imgur.com/LNWNxyk.png)

**Comment by Alayan-stk-2** [comment]
There are two latest post message. One is for the 0.9.3 release, one is really the latest post. I don't know how this works.

Otherwise, there is a clear formatting issue (no separation between blog address and post title) but with your issue title, there is no way to know what you are talking about specifically.

**Comment by qwertychouskie** [comment]
The formatting issue mainly, though also calling the release post "Latest release announcement:" would be nice.

**Comment by leyyin** [comment]
Should be fixed.

**Comment by Alayan-stk-2** [comment]
Fixed on my side.
