### ISSUE TITLE
addons site not visible on stk website

### ISSUE THREAD

**Issue by Cyrille37** [supertuxkart/stk-addons#54]
Hi

The addons website url is very hard to find. It's not in pages
- http://supertuxkart.sourceforge.net/Main_Page
- http://supertuxkart.sourceforge.net/Discover

And in page http://supertuxkart.sourceforge.net/Get_involved it's only about "submit a add-on" which is not understandable by end-users (players).

Cheers and thousand Thanks for STK !

**Comment by Cyrille37** [comment]
Another sub-task : explain that http://stkaddons.net/ is readonly for history and annonce the new one addons.supertuxkart.net

btw: the page http://supertuxkart.sourceforge.net/Get_involved directing to http://stkaddons.net/

**Comment by auriamg** [comment]
I've done a few adjustments, it should be much better now. I think we can close this?

**Comment by Cyrille37** [comment]
Great. Thanks.

But what about greats addons on http://stkaddons.net/ ? They're going to trash ?

**Comment by konstin** [comment]
The site will stay in read-only mode for some time, i.e. you can still download the add-ons. But due to the huge graphical improvements, the add-ons can't just be moved to the new stkaddons-site. Instead, every artist needs to make sure his/her add-ons fit to the new style guidelines, propably improve the artwork to make use of the new features and then upload it to the add-ons page.

**Comment by Cyrille37** [comment]
Thanks

**Comment by konstin** [comment]
All links in the wiki should now point to the new add-ons website because even the [fulltext search](http://supertuxkart.sourceforge.net/site/index.php?title=Special:Search&search=stkaddons.net&fulltext=Search&ns0=1&ns1=1&ns2=1&ns3=1&ns4=1&ns5=1&ns6=1&ns7=1&ns8=1&ns9=1&ns10=1&ns11=1&ns12=1&ns13=1&ns14=1&ns15=1&ns100=1&ns101=1&ns102=1&ns103=1&redirs=0) doesn't find "stkaddons.net" anymore
