### ISSUE TITLE
where is documentation to make Kart and Track ?

### ISSUE THREAD

**Issue by Cyrille37** [supertuxkart/stk-addons#59]
Hi,
Sorry to use the bug tracker for such question, but I'd starting to create a Kart and a Track then SF.net gone down. I did not saved statics pages.

Could some one put somewhere those documentation that permits to construct Supertuxkart stuff.

Thanks a lot & Cheers

**Comment by auriamg** [comment]
Hi,

they would be found on our website (supertuxkart.net), there are pages for
that. Unfortunately, the website is currently unavailable because our host
(sourceforge) is currently experiencing difficulties. You can find a cached
version on google

http://webcache.googleusercontent.com/search?q=cache:hJZgVICdsUoJ:supertuxkart.sourceforge.net/Track_Maker%27s_Guide+&cd=1&hl=en&ct=clnk&gl=ca
http://webcache.googleusercontent.com/search?q=cache:uvNi0G7BK_gJ:supertuxkart.sourceforge.net/Installing_the_tools+&cd=1&hl=fr&ct=clnk&gl=ca

Another very helpful resource is to checkout our media repository (
http://webcache.googleusercontent.com/search?q=cache:y0T-IYWNiHgJ:supertuxkart.sourceforge.net/Media_Repo+&cd=1&hl=fr&ct=clnk&gl=ca
), you can take a look at how current tracks are made.

Hope this helps, don't hesitate to ask further questions or come on IRC

-- Auria



On Wed, Jul 22, 2015 at 12:36 PM, Cyrille Giquello <notifications@github.com

**Comment by auriamg** [comment]
Hi again.

the website is now back again :) So you can directly check these

http://supertuxkart.sourceforge.net/Kart_resources_index
http://supertuxkart.sourceforge.net/Track_Maker%27s_Guide

-- Auria

**Comment by Cyrille37** [comment]
Thanks a lot, you're lovelly !
Nice that the SF infra came back ... Ouf!
So we can go back to work on a new Kart !
