### ISSUE TITLE
Problems creating server

### ISSUE THREAD

**Issue by hiker** [supertuxkart/stk-addons#63]
When the 'create' command is sent to the server, it only expects name and max-player as parameter, not the ip address or port.  api/server.php then passes 0 as ip address and port to createServer.

This then results in an error (since atm there is already one server on 0.0.0.0:0), and no server can be created.

It appears that the a second command is expected ('set') which will set the ip address and port, and/or start which appears to do something similar. I don't know how the protocol is supposed to work :(

Is there a reason for this two-step process? STK could provide the public ip address and port number in this request (though the 'start' command also takes a second port number as parameter ('private-port'), at this stage I am not sure what this exactly is). Even if the 0:0 address would be only temporary, it's not a viable solution (since more than one server might be created at the same time).

**Comment by konstin** [comment]
I'm pretty sure it doesn't work that way because I could set up a server using my own stkaddons. Though I never actually had a real race because I didn't have the time to figure out how to start a networked race. I assume that the class that should fetch commands from the terminal doesn't work (anymore). I'll hopefully find time to re-check this at some point, but until then I suggest https://www.youtube.com/watch?v=J8oTmEpDGss and manually setting the IP address in the STUN class to 127.0.0.1 (you probably need some bit-shifting or write it as hex, whatever you prefer), because I found those two somehow helpful.

**Comment by hiker** [comment]
Hi Konstin,

thanks for your comment, but don't waste your time on this (you could run this because your addon server doesn't have a server defined at 0.0.0.0:0, which we have on stkaddons atm - the main point is that this should never prevent a new server from starting).  Also note that the console is disabled in release mode iirc (at least it causes a crash on exit on windows otherwise).
