### ISSUE TITLE
Improvements to server protocol

### ISSUE THREAD

**Issue by hiker** [supertuxkart/stk-addons#65]
We need some changes, and some further improvements would help simplifying the STK server code. I'll list them all in one ticket, I don't think any of them would be difficult to implement:
- [ ] A new 'register' function to register a server. This is basically the same as 'start', but it should also take the server name from the query (the way it is done in the 'create' command). This would finally allow server creation with the user specified name (and not only 'Temporary name').
- [ ] When querying for all servers ('get-all'), return the ip address, and public and private port of each server. This way we save one additional query to the stk server to get this later.
- [ ] When a client tries to connect to a server, it adds an entry to server_conn. The server polls this table. When it finds a new entry, it needs to query the server again to find the ip address of the client. Those two requests can be combined into one query: just return the client's ip address, and private and public port when a server polls.

Some other commands can then be removed (at a later stage).

**Comment by auriamg** [comment]
I pushed implementations for the first two points in branch Issue65 ( 55b5d342fcc8c4239bc19d8c432ee05c10a19d4e )

For the first item, I wonder if a new command is really required? Why not simply pass an (optional) server name to the 'start' command?

For point 3, I may need a bit more explanations as I am not sure I understand

**Comment by leyyin** [comment]
For point 3 I believe when the [server polls](https://github.com/supertuxkart/stk-addons/blob/55b5d342fcc8c4239bc19d8c432ee05c10a19d4e/api/server.php#L232) it should also return the info returned in [`get`](https://github.com/supertuxkart/stk-addons/blob/55b5d342fcc8c4239bc19d8c432ee05c10a19d4e/api/server.php#L147)(IP, port, private port). For this to happen, in [`ClientSession::getServerConnectionRequests`](https://github.com/supertuxkart/stk-addons/blob/master/include/ClientSession.class.php#L284) there needs to be a join with the `client_sessions` table.
So that instead of the server polling for the peer ids and requesting the info for each peer individually, all is done in one poll request.

**Comment by hiker** [comment]
Re a new command instead of improving the other: I don't know why it was done this way originally, so I was afraid that adding more to an existing command might break some other things. But I think by now I understand a bit more of the STK side of things, so I am happy to just extend the existing command.

The other/main problem is (from memory) that the first command has no ip address, so it will use 0, and since the IP address is a primary key, creation of a new row fails because of that. So if we improve the first/existing command, it would also need an ip address and port number.

**Comment by hiker** [comment]
Point 3: leyyin is right. ATM the server needs two queries to connect to a client: first a regular polling to find any clients that want to connect. Once the server knows about the client(s) to connect, it then queries the addon server again to find the ip address (etc) of the clients. Getting the IP address with the information that a client wants to connect simplifies the protocols

**Comment by auriamg** [comment]
Okay third point done. 9535c61f1a2681c94b89e45af91dd35a6be499a8

One question, did it ever work? It was reading "userid" from the sql query response but the field is actually named "user_id", so I wonder if I missed something or it really never worked?

@leyyin Since I'm not to php/mysql/stk-addons, I'd appreciate if you could take a quick look to make sure my changes seem okay to you?

**Comment by leyyin** [comment]
@auriamg just by looking at the code everything seems fine to me. I do not think that that feature ever worked, a certain someone forgot to update that code after refactoring *cough*.

**Comment by auriamg** [comment]
Thanks, I think we could probably merge the branch. @leyyin what procedure is used to deploy changes? is there a tool or procedure to deploy files to stk-addons, or do you just copy the files manually?

**Comment by leyyin** [comment]
@auriamg I do it usually by hand with the help of git. More details are in the shared google document shared by the team. I guess I can make a simple deploy script.

**Comment by konstin** [comment]
Slightly off-topic: I've recently added [autodeploy](https://github.com/logsol/Github-Auto-Deploy) to the wiki and I think this might also be useful to stk-addons.

**Comment by qwertychouskie** [comment]
Where is the GitHub repo for the wiki?

**Comment by qwertychouskie** [comment]
Can this be closed now as all three points have been fixed?

**Comment by auriamg** [comment]
@qwertychouskie we will close the ticket when we're done. This change has not yet been deployed in production and the c++ side is not yet adapted for the new protocol.

**Comment by qwertychouskie** [comment]
Oh, OK.  Sorry, didn't realize there was more to do.

**Comment by Benau** [comment]
Now all should be ready
